
// import type { Metadata } from "next";
// import Navbar from "./components/navbar";
// import { Inter ,Outfit} from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import { useEffect, useState } from "react";
// const outfit = Outfit({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
  
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={outfit.className}>
//         <Navbar/>
        
//         {children}</body>
//     </html>
//     </ClerkProvider>
//   );
// }
// app/layout.tsx or app/RootLayout.tsx
import type { Metadata } from "next";
import Navbar from "./components/navbar";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
// import { SignUp } from "@clerk/nextjs";
const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Navbar />
          {/* <SignIn/>sign-in\[[...sign-in]] */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
